### ISSUE TITLE
Repro - Aurora Text Doesn't Animate

### ISSUE THREAD

**Issue by drewlowe** [magicuidesign/magicui#624]
**Describe the bug**
AFAIK, the AuroraText component does not animate. I have:
1. Copied in the `tailwind.config.cjs` file
2. Installed `tailwindcss-animate`
3. Reproduced in a new repo

**To Reproduce**
1. Go to https://github.com/drewlowe/aurora-text-bug-repro
2. `npm run dev`

**Expected behavior**
The gradient text shows, but it does not have the expected motion behavior. I see there has been some activity on this component recently in the git history, so maybe something accidentally broke in the process?

**Desktop (please complete the following information):**
 - OS: **Aurora 41** (Ironic lol)
 - Browser: **Chromium**
 - Version: 134.0.6998.117 (Official Build) (64-bit)

**Comment by drewlowe** [comment]
I got a working solution by adding these styles to `global.css`:

```css
@keyframes aurora {
	0% {
		background-position: 0 50%;
		transform: rotate(-5deg) scale(0.9);
	}
	25% {
		background-position: 50% 100%;
		transform: rotate(5deg) scale(1.1);
	}
	50% {
		background-position: 100% 50%;
		transform: rotate(-3deg) scale(0.95);
	}
	75% {
		background-position: 50% 0;
		transform: rotate(3deg) scale(1.05);
	}
	100% {
		background-position: 0 50%;
		transform: rotate(-5deg) scale(0.9);
	}
}

.aurora-text {
	background-size: 200% auto;
	animation: aurora 15s ease-in-out infinite alternate;
}
```

I think the documentation should have a reference for adding styles (v4) or tailwind config (v3). I will try to put up a PR if I have some time later. Thank you Magic UI team for the amazing components. 💙💜🩷🩵
