### ISSUE TITLE
[bug]: /docs/components/line-shadow-text

### ISSUE THREAD

**Issue by jahangeer-dev** [magicuidesign/magicui#655]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
the animation is not working as expected only the bars are appears

**Comment by ignaigna** [comment]
add 
```css
@theme inline {
  --animate-line-shadow: line-shadow 15s linear infinite;
 
  @keyframes line-shadow {
    0% {
      background-position: 0 0;
    }
    100% {
      background-position: 100% -100%;
    }
  }
}
```
to your tailwind CSS file or similar
