### ISSUE TITLE
[bug]: /docs/components/retro-grid

### ISSUE THREAD

**Issue by Osademe-e** [magicuidesign/magicui#700]
# Bug Report: CSS Animation Not Working in Tailwind v4+

## **Describe the bug**

The following CSS code does not work in Tailwind v4+:

```css
@theme inline {
  --animate-grid: grid 15s linear infinite;
 
  @keyframes grid {
    0% {
      transform: translateY(-50%);
    }
    100% {
      transform: translateY(0);
    }
  }
}
```

## **To Reproduce**

1. Go to https://magicui.design/docs/components/retro-grid
2. Click on **Manual Installation**
3. Scroll down to **Add the required CSS animations**
4. See error: Code is not functional

## **Expected behavior**

The correct code for the CSS should be:

```css
@layer base {
  :root {
    --animate-grid: grid 15s linear infinite;
  }
}

@keyframes grid {
  0% {
    transform: translateY(-50%);
  }
  100% {
    transform: translateY(0);
  }
}

.animate-grid {
  animation: var(--animate-grid);
}
```

## **Desktop Environment**

- **OS:** macOS
- **Browser:** Chrome
- **Version:** 137.0.7151.56
